package com.xlzhen.dlnavideodownload.utils;

import java.util.HashMap;
import java.util.Map;

public class MimeTypeUtils {
    private static Map<String,String> mimeMap;
    private static Map<String,String> extMap;

    public static String getMimeType(String ext){
        if(mimeMap==null){
            mimeMap=new HashMap<>();
            mimeMap.put("cbz","application/x-cbz");
            mimeMap.put("atom","application/atom+xml");
            mimeMap.put("rtx","audio/midi");
            mimeMap.put("iso","application/x-iso9660-image");
            mimeMap.put("kpr","application/x-kpresenter");
            mimeMap.put("com","application/x-msdos-program");
            mimeMap.put("rgb","image/x-rgb");
            mimeMap.put("ots","application/vnd.oasis.opendocument.spreadsheet-template");
            mimeMap.put("pfr","application/font-tdpfr");
            mimeMap.put("mol2","chemical/x-mol2");
            mimeMap.put("inp","chemical/x-gamess-input");
            mimeMap.put("vmd","chemical/x-vmd");
            mimeMap.put("spl","application/x-futuresplash");
            mimeMap.put("avi","video/avi");
            mimeMap.put("cmdf","chemical/x-cmdf");
            mimeMap.put("qtl","application/x-quicktimeplayer");
            mimeMap.put("rd","chemical/x-mdl-rdfile");
            mimeMap.put("mxu","video/vnd.mpegurl");
            mimeMap.put("xml","text/xml");
            mimeMap.put("nc","application/x-netcdf");
            mimeMap.put("rss","application/rss+xml");
            mimeMap.put("tcl","application/x-tcl");
            mimeMap.put("uls","text/iuls");
            mimeMap.put("vcf","text/vcard");
            mimeMap.put("ota","application/vnd.android.ota");
            mimeMap.put("sda","application/vnd.stardivision.draw");
            mimeMap.put("html","text/html");
            mimeMap.put("xpm","image/x-xpixmap");
            mimeMap.put("cbr","application/x-cbr");
            mimeMap.put("ros","chemical/x-rosdal");
            mimeMap.put("mov","video/quicktime");
            mimeMap.put("mp4","video/mp4");
            mimeMap.put("sh","application/x-sh");
            mimeMap.put("cdx","chemical/x-cdx");
            mimeMap.put("key","application/pgp-keys");
            mimeMap.put("webm","video/webm");
            mimeMap.put("wma","audio/x-ms-wma");
            mimeMap.put("djvu","image/vnd.djvu");
            mimeMap.put("ly","text/x-lilypond");
            mimeMap.put("src","application/x-wais-source");
            mimeMap.put("psd","image/x-photoshop");
            mimeMap.put("wm","video/x-ms-wm");
            mimeMap.put("jar","application/java-archive");
            mimeMap.put("sfd","application/vnd.font-fontforge-sfd");
            mimeMap.put("xlsm","application/vnd.ms-excel.sheet.macroenabled.12");
            mimeMap.put("heif","image/heif");
            mimeMap.put("dotm","application/vnd.ms-word.template.macroenabled.12");
            mimeMap.put("heic","image/heic");
            mimeMap.put("pls","audio/x-scpls");
            mimeMap.put("bsd","chemical/x-crossfire");
            mimeMap.put("mdb","application/msaccess");
            mimeMap.put("cpt","application/mac-compactpro");
            mimeMap.put("3gpp","video/3gpp");
            mimeMap.put("pgn","application/x-chess-pgn");
            mimeMap.put("sisx","x-epoc/x-sisx-app");
            mimeMap.put("xltx","application/vnd.openxmlformats-officedocument.spreadsheetml.template");
            mimeMap.put("cap","application/vnd.tcpdump.pcap");
            mimeMap.put("cdf","application/x-cdf");
            mimeMap.put("cac","chemical/x-cache");
            mimeMap.put("cur","image/ico");
            mimeMap.put("sdd","application/vnd.stardivision.impress");
            mimeMap.put("zip","application/zip");
            mimeMap.put("xsl","application/xslt+xml");
            mimeMap.put("scr","application/x-silverlight");
            mimeMap.put("cub","chemical/x-gaussian-cube");
            mimeMap.put("ice","x-conference/x-cooltalk");
            mimeMap.put("ttf","font/sfnt");
            mimeMap.put("msi","application/x-msi");
            mimeMap.put("webp","image/webp");
            mimeMap.put("ra","audio/x-realaudio");
            mimeMap.put("323","text/h323");
            mimeMap.put("ts","video/mp2t");
            mimeMap.put("m3u8","application/vnd.apple.mpegurl");
            mimeMap.put("thmx","application/vnd.ms-officetheme");
            mimeMap.put("kil","application/x-killustrator");
            mimeMap.put("kmz","application/vnd.google-earth.kmz");
            mimeMap.put("srw","image/x-samsung-srw");
            mimeMap.put("aif","audio/x-aiff");
            mimeMap.put("mpeg","video/mp2p");
            mimeMap.put("sgl","application/vnd.stardivision.writer-global");
            mimeMap.put("dmg","application/x-apple-diskimage");
            mimeMap.put("cer","application/pkix-cert");
            mimeMap.put("wvx","video/x-ms-wvx");
            mimeMap.put("tcl","text/x-tcl");
            mimeMap.put("rtf","application/rtf");
            mimeMap.put("awb","audio/amr-wb");
            mimeMap.put("istr","chemical/x-isostar");
            mimeMap.put("sd2","audio/x-sd2");
            mimeMap.put("ppm","image/x-portable-pixmap");
            mimeMap.put("gcd","text/x-pcs-gcd");
            mimeMap.put("pdb","chemical/x-pdb");
            mimeMap.put("xz","application/x-xz");
            mimeMap.put("wp5","application/vnd.wordperfect5.1");
            mimeMap.put("p7r","application/x-pkcs7-certreqresp");
            mimeMap.put("nwc","application/x-nwc");
            mimeMap.put("crl","application/x-pkcs7-crl");
            mimeMap.put("cif","chemical/x-cif");
            mimeMap.put("dff","audio/x-dff");
            mimeMap.put("cab","application/x-cab");
            mimeMap.put("dcr","application/x-director");
            mimeMap.put("erf","image/x-epson-erf");
            mimeMap.put("srt","application/x-subrip");
            mimeMap.put("dsd","audio/dsd");
            mimeMap.put("ttf","font/otf");
            mimeMap.put("rss","application/x-rss+xml");
            mimeMap.put("png","image/png");
            mimeMap.put("rpm","application/x-redhat-package-manager");
            mimeMap.put("jmz","application/x-jmol");
            mimeMap.put("sh","text/x-sh");
            mimeMap.put("xwd","image/x-xwindowdump");
            mimeMap.put("cpio","application/x-cpio");
            mimeMap.put("pcf","application/x-font-pcf");
            mimeMap.put("movie","video/x-sgi-movie");
            mimeMap.put("sds","application/vnd.stardivision.chart");
            mimeMap.put("oga","audio/ogg");
            mimeMap.put("otp","application/vnd.oasis.opendocument.presentation-template");
            mimeMap.put("tgz","application/x-gtar-compressed");
            mimeMap.put("tar","application/x-tar");
            mimeMap.put("tex","text/x-tex");
            mimeMap.put("atomsrv","application/atomserv+xml");
            mimeMap.put("prt","chemical/x-ncbi-asn1-ascii");
            mimeMap.put("gcg","chemical/x-gcg8-sequence");
            mimeMap.put("pgm","image/x-portable-graymap");
            mimeMap.put("dotx","application/vnd.openxmlformats-officedocument.wordprocessingml.template");
            mimeMap.put("yt","application/vnd.youtube.yt");
            mimeMap.put("swf","application/x-shockwave-flash");
            mimeMap.put("csd","audio/csound");
            mimeMap.put("pptm","application/vnd.ms-powerpoint.presentation.macroenabled.12");
            mimeMap.put("java","text/x-java");
            mimeMap.put("ustar","application/x-ustar");
            mimeMap.put("sdc","application/vnd.stardivision.calc");
            mimeMap.put("hin","chemical/x-hin");
            mimeMap.put("xcf","application/x-xcf");
            mimeMap.put("epub","application/epub+zip");
            mimeMap.put("ott","application/vnd.oasis.opendocument.text-template");
            mimeMap.put("mka","audio/x-matroska");
            mimeMap.put("hdf","application/x-hdf");
            mimeMap.put("texinfo","application/x-texinfo");
            mimeMap.put("sis","application/vnd.symbian.install");
            mimeMap.put("mml","text/mathml");
            mimeMap.put("gan","application/x-ganttproject");
            mimeMap.put("sxm","application/vnd.sun.xml.math");
            mimeMap.put("bmp","image/bmp");
            mimeMap.put("gf","application/x-tex-gf");
            mimeMap.put("mxmf","audio/mobile-xmf");
            mimeMap.put("mmf","application/vnd.smaf");
            mimeMap.put("ras","image/x-cmu-raster");
            mimeMap.put("cod","application/vnd.rim.cod");
            mimeMap.put("csv","text/comma-separated-values");
            mimeMap.put("application","application/x-ms-application");
            mimeMap.put("iii","application/x-iphone");
            mimeMap.put("sxw","application/vnd.sun.xml.writer");
            mimeMap.put("dng","image/x-adobe-dng");
            mimeMap.put("qcp","audio/qcelp");
            mimeMap.put("ins","application/x-internet-signup");
            mimeMap.put("wasm","application/wasm");
            mimeMap.put("ppam","application/vnd.ms-powerpoint.addin.macroenabled.12");
            mimeMap.put("ppt","application/vnd.ms-powerpoint");
            mimeMap.put("cpp","text/x-c++src");
            mimeMap.put("tiff","image/tiff");
            mimeMap.put("pef","image/x-pentax-pef");
            mimeMap.put("sit","application/x-stuffit");
            mimeMap.put("scala","text/x-scala");
            mimeMap.put("wbxml","application/vnd.wap.wbxml");
            mimeMap.put("wmd","application/x-ms-wmd");
            mimeMap.put("mkv","video/x-matroska");
            mimeMap.put("gau","chemical/x-gaussian-input");
            mimeMap.put("sxc","application/vnd.sun.xml.calc");
            mimeMap.put("xbm","image/x-xbitmap");
            mimeMap.put("otg","application/vnd.oasis.opendocument.graphics-template");
            mimeMap.put("ica","application/x-ica");
            mimeMap.put("sgf","application/x-go-sgf");
            mimeMap.put("c","text/x-csrc");
            mimeMap.put("otf","application/font-sfnt");
            mimeMap.put("oth","application/vnd.oasis.opendocument.text-web");
            mimeMap.put("wmz","application/x-ms-wmz");
            mimeMap.put("wav","audio/x-wav");
            mimeMap.put("mcif","chemical/x-mmcif");
            mimeMap.put("frm","application/x-maker");
            mimeMap.put("b","chemical/x-molconn-z");
            mimeMap.put("ttf","font/ttf");
            mimeMap.put("etx","text/x-setext");
            mimeMap.put("crt","application/x-x509-user-cert");
            mimeMap.put("cpa","chemical/x-compass");
            mimeMap.put("mcm","chemical/x-macmolecule");
            mimeMap.put("bin","application/octet-stream");
            mimeMap.put("fl","application/x-android-drm-fl");
            mimeMap.put("pcx","image/pcx");
            mimeMap.put("asf","video/x-ms-asf");
            mimeMap.put("rdf","application/rdf+xml");
            mimeMap.put("jnlp","application/x-java-jnlp-file");
            mimeMap.put("sv4crc","application/x-sv4crc");
            mimeMap.put("kml","application/vnd.google-earth.kml+xml");
            mimeMap.put("3gpp2","video/3gpp2");
            mimeMap.put("mng","video/x-mng");
            mimeMap.put("tsp","application/dsptype");
            mimeMap.put("aac","audio/aac");
            mimeMap.put("mp3","audio/mpeg");
            mimeMap.put("davmount","application/davmount+xml");
            mimeMap.put("lha","application/x-lha");
            mimeMap.put("p","text/x-pascal");
            mimeMap.put("wad","application/x-doom");
            mimeMap.put("jad","text/vnd.sun.j2me.app-descriptor");
            mimeMap.put("odp","application/vnd.oasis.opendocument.presentation");
            mimeMap.put("art","image/x-jg");
            mimeMap.put("ac3","audio/ac3");
            mimeMap.put("deb","application/vnd.debian.binary-package");
            mimeMap.put("moc","text/x-moc");
            mimeMap.put("m3u","audio/x-mpegurl");
            mimeMap.put("ogx","application/ogg");
            mimeMap.put("ico","image/x-icon");
            mimeMap.put("pac","application/x-ns-proxy-autoconfig");
            mimeMap.put("svg","image/svg+xml");
            mimeMap.put("ttl","text/turtle");
            mimeMap.put("alc","chemical/x-alchemy");
            mimeMap.put("ec3","audio/eac3");
            mimeMap.put("xml","application/x-wifi-config");
            mimeMap.put("sci","application/x-scilab");
            mimeMap.put("wrf","video/x-webex");
            mimeMap.put("prf","application/pics-rules");
            mimeMap.put("nb","application/mathematica");
            mimeMap.put("odi","application/vnd.oasis.opendocument.image");
            mimeMap.put("mp3","audio/x-mpeg");
            mimeMap.put("atomcat","application/atomcat+xml");
            mimeMap.put("hs","text/x-haskell");
            mimeMap.put("vcf","text/x-vcard");
            mimeMap.put("apk","application/vnd.android.package-archive");
            mimeMap.put("pyc","application/x-python-code");
            mimeMap.put("axa","audio/annodex");
            mimeMap.put("flac","application/x-flac");
            mimeMap.put("gnumeric","application/x-gnumeric");
            mimeMap.put("mm","application/x-freemind");
            mimeMap.put("nef","image/x-nikon-nef");
            mimeMap.put("xpi","application/x-xpinstall");
            mimeMap.put("pnm","image/x-portable-anymap");
            mimeMap.put("csml","chemical/x-csml");
            mimeMap.put("sw","chemical/x-swissprot");
            mimeMap.put("hta","application/hta");
            mimeMap.put("eml","message/rfc822");
            mimeMap.put("vsd","application/vnd.visio");
            mimeMap.put("dif","video/dv");
            mimeMap.put("csh","application/x-csh");
            mimeMap.put("bmp","image/x-ms-bmp");
            mimeMap.put("avi","video/x-msvideo");
            mimeMap.put("ppsm","application/vnd.ms-powerpoint.slideshow.macroenabled.12");
            mimeMap.put("sldx","application/vnd.openxmlformats-officedocument.presentationml.slide");
            mimeMap.put("vms","chemical/x-vamas-iso14976");
            mimeMap.put("es","application/ecmascript");
            mimeMap.put("mvb","chemical/x-mopac-vib");
            mimeMap.put("cxf","chemical/x-cxf");
            mimeMap.put("m4a","audio/mp4");
            mimeMap.put("imy","audio/imelody");
            mimeMap.put("docm","application/vnd.ms-word.document.macroenabled.12");
            mimeMap.put("pdf","application/pdf");
            mimeMap.put("sid","audio/prs.sid");
            mimeMap.put("pgp","application/pgp-encrypted");
            mimeMap.put("wmlc","application/vnd.wap.wmlc");
            mimeMap.put("torrent","application/x-bittorrent");
            mimeMap.put("pl","text/x-perl");
            mimeMap.put("opf","application/oebps-package+xml");
            mimeMap.put("abw","application/x-abiword");
            mimeMap.put("p12","application/x-pkcs12");
            mimeMap.put("pat","image/x-coreldrawpattern");
            mimeMap.put("~","application/x-trash");
            mimeMap.put("wpl","application/vnd.ms-wpl");
            mimeMap.put("csv","text/csv");
            mimeMap.put("ico","image/vnd.microsoft.icon");
            mimeMap.put("dl","video/dl");
            mimeMap.put("rxn","chemical/x-mdl-rxnfile");
            mimeMap.put("css","text/css");
            mimeMap.put("d","text/x-dsrc");
            mimeMap.put("stw","application/vnd.sun.xml.writer.template");
            mimeMap.put("wpd","application/vnd.wordperfect");
            mimeMap.put("hpp","text/x-c++hdr");
            mimeMap.put("ms","application/x-troff-ms");
            mimeMap.put("one","application/onenote");
            mimeMap.put("kin","chemical/x-kinemage");
            mimeMap.put("info","application/x-info");
            mimeMap.put("xtel","chemical/x-xtel");
            mimeMap.put("wrl","model/vrml");
            mimeMap.put("mif","application/x-mif");
            mimeMap.put("gen","chemical/x-genbank");
            mimeMap.put("bib","text/x-bibtex");
            mimeMap.put("js","application/javascript");
            mimeMap.put("stc","application/vnd.sun.xml.calc.template");
            mimeMap.put("me","application/x-troff-me");
            mimeMap.put("gl","video/gl");
            mimeMap.put("dvi","application/x-dvi");
            mimeMap.put("latex","application/x-latex");
            mimeMap.put("jam","application/x-jam");
            mimeMap.put("pk","application/x-tex-pk");
            mimeMap.put("sxg","application/vnd.sun.xml.writer.global");
            mimeMap.put("dsf","audio/x-dsf");
            mimeMap.put("x3d","model/x3d+xml");
            mimeMap.put("ctx","chemical/x-ctx");
            mimeMap.put("fch","chemical/x-gaussian-checkpoint");
            mimeMap.put("ttml","application/ttml+xml");
            mimeMap.put("mpeg","video/mpeg");
            mimeMap.put("xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
            mimeMap.put("sct","text/scriptlet");
            mimeMap.put("rw2","image/x-panasonic-rw2");
            mimeMap.put("oda","application/oda");
            mimeMap.put("wk","application/x-123");
            mimeMap.put("odm","application/vnd.oasis.opendocument.text-master");
            mimeMap.put("stl","application/sla");
            mimeMap.put("boo","text/x-boo");
            mimeMap.put("tsv","text/tab-separated-values");
            mimeMap.put("tgf","chemical/x-mdl-tgf");
            mimeMap.put("gif","image/gif");
            mimeMap.put("class","application/java-vm");
            mimeMap.put("ez","application/andrew-inset");
            mimeMap.put("crt","application/x-x509-server-cert");
            mimeMap.put("sdf","application/vnd.stardivision.math");
            mimeMap.put("sdp","application/sdp");
            mimeMap.put("cer","chemical/x-cerius");
            mimeMap.put("mph","application/x-comsol");
            mimeMap.put("ogv","video/ogg");
            mimeMap.put("cbin","chemical/x-cactvs-binary");
            mimeMap.put("jdx","chemical/x-jcamp-dx");
            mimeMap.put("rtf","text/rtf");
            mimeMap.put("doc","application/msword");
            mimeMap.put("jpm","image/jpm");
            mimeMap.put("m3u","audio/mpegurl");
            mimeMap.put("jpx","image/jpx");
            mimeMap.put("appcache","text/cache-manifest");
            mimeMap.put("odt","application/vnd.oasis.opendocument.text");
            mimeMap.put("bcpio","application/x-bcpio");
            mimeMap.put("skp","application/x-koan");
            mimeMap.put("fig","application/x-xfig");
            mimeMap.put("val","chemical/x-ncbi-asn1-binary");
            mimeMap.put("potm","application/vnd.ms-powerpoint.template.macroenabled.12");
            mimeMap.put("wbmp","image/vnd.wap.wbmp");
            mimeMap.put("emb","chemical/x-embl-dl-nucleotide");
            mimeMap.put("csh","text/x-csh");
            mimeMap.put("woff","font/woff");
            mimeMap.put("x3dv","model/x3d+vrml");
            mimeMap.put("asn","chemical/x-ncbi-asn1");
            mimeMap.put("ape","audio/x-ape");
            mimeMap.put("m3u8","application/x-mpegurl");
            mimeMap.put("crw","image/x-canon-crw");
            mimeMap.put("sql","application/x-sql");
            mimeMap.put("ksp","application/x-kspread");
            mimeMap.put("ra","audio/x-pn-realaudio");
            mimeMap.put("axv","video/annodex");
            mimeMap.put("cu","application/cu-seeme");
            mimeMap.put("txt","text/plain");
            mimeMap.put("vrm","x-world/x-vrml");
            mimeMap.put("cpt","image/x-corelphotopaint");
            mimeMap.put("moo","chemical/x-mopac-out");
            mimeMap.put("pfa","application/x-font");
            mimeMap.put("aac","audio/aac-adts");
            mimeMap.put("manifest","application/x-ms-manifest");
            mimeMap.put("gpt","chemical/x-mopac-graph");
            mimeMap.put("wmls","text/vnd.wap.wmlscript");
            mimeMap.put("xltm","application/vnd.ms-excel.template.macroenabled.12");
            mimeMap.put("mbox","application/mbox");
            mimeMap.put("sti","application/vnd.sun.xml.impress.template");
            mimeMap.put("odf","application/vnd.oasis.opendocument.formula");
            mimeMap.put("x3db","model/x3d+binary");
            mimeMap.put("pgp","application/pgp-signature");
            mimeMap.put("cdr","image/x-coreldraw");
            mimeMap.put("c3d","chemical/x-chem3d");
            mimeMap.put("xul","application/vnd.mozilla.xul+xml");
            mimeMap.put("cdt","image/x-coreldrawtemplate");
            mimeMap.put("t","application/x-troff");
            mimeMap.put("webarchivexml","application/x-webarchive-xml");
            mimeMap.put("std","application/vnd.sun.xml.draw.template");
            mimeMap.put("heics","image/heic-sequence");
            mimeMap.put("pbm","image/x-portable-bitmap");
            mimeMap.put("m3g","application/m3g");
            mimeMap.put("dms","application/x-dms");
            mimeMap.put("xcos","application/x-scilab-xcos");
            mimeMap.put("mop","chemical/x-mopac-input");
            mimeMap.put("xls","application/vnd.ms-excel");
            mimeMap.put("vcs","text/x-vcalendar");
            mimeMap.put("sv4cpio","application/x-sv4cpio");
            mimeMap.put("woff2","font/woff2");
            mimeMap.put("json","application/json");
            mimeMap.put("man","application/x-troff-man");
            mimeMap.put("amr","audio/amr");
            mimeMap.put("tm","text/texmacs");
            mimeMap.put("pptx","application/vnd.openxmlformats-officedocument.presentationml.presentation");
            mimeMap.put("diff","text/x-diff");
            mimeMap.put("odb","application/vnd.oasis.opendocument.database");
            mimeMap.put("raf","image/x-fuji-raf");
            mimeMap.put("m4v","video/m4v");
            mimeMap.put("oza","application/x-oz-application");
            mimeMap.put("lhs","text/x-literate-haskell");
            mimeMap.put("ics","text/calendar");
            mimeMap.put("xml","application/xml");
            mimeMap.put("sd","chemical/x-mdl-sdfile");
            mimeMap.put("qgs","application/x-qgis");
            mimeMap.put("sfv","text/x-sfv");
            mimeMap.put("jng","image/x-jng");
            mimeMap.put("mxf","application/mxf");
            mimeMap.put("mol","chemical/x-mdl-molfile");
            mimeMap.put("phps","text/text");
            mimeMap.put("cdy","application/vnd.cinderella");
            mimeMap.put("ts","video/mp2ts");
            mimeMap.put("ps","application/postscript");
            mimeMap.put("xhtml","application/xhtml+xml");
            mimeMap.put("hwp","application/x-hwp");
            mimeMap.put("htc","text/x-component");
            mimeMap.put("cml","chemical/x-cml");
            mimeMap.put("anx","application/annodex");
            mimeMap.put("chm","chemical/x-chemdraw");
            mimeMap.put("snd","audio/basic");
            mimeMap.put("arw","image/x-sony-arw");
            mimeMap.put("h","text/x-chdr");
            mimeMap.put("cr2","image/x-canon-cr2");
            mimeMap.put("orf","image/x-olympus-orf");
            mimeMap.put("hqx","application/mac-binhex40");
            mimeMap.put("jp2","image/jp2");
            mimeMap.put("potx","application/vnd.openxmlformats-officedocument.presentationml.template");
            mimeMap.put("rar","application/rar");
            mimeMap.put("rb","application/x-ruby");
            mimeMap.put("sxd","application/vnd.sun.xml.draw");
            mimeMap.put("gtar","application/x-gtar");
            mimeMap.put("ief","image/ief");
            mimeMap.put("jsonld","application/ld+json");
            mimeMap.put("sdw","application/vnd.stardivision.writer");
            mimeMap.put("xlam","application/vnd.ms-excel.addin.macroenabled.12");
            mimeMap.put("wz","application/x-wingz");
            mimeMap.put("o","application/x-object");
            mimeMap.put("rdp","application/x-rdp");
            mimeMap.put("heifs","image/heif-sequence");
            mimeMap.put("docx","application/vnd.openxmlformats-officedocument.wordprocessingml.document");
            mimeMap.put("sldm","application/vnd.ms-powerpoint.slide.macroenabled.12");
            mimeMap.put("vcd","application/x-cdlink");
            mimeMap.put("lin","application/bbolin");
            mimeMap.put("nrw","image/x-nikon-nrw");
            mimeMap.put("cat","application/vnd.ms-pki.seccat");
            mimeMap.put("mmd","chemical/x-macromodel-input");
            mimeMap.put("lyx","application/x-lyx");
            mimeMap.put("lsf","video/x-la-asf");
            mimeMap.put("smi","application/smil+xml");
            mimeMap.put("odg","application/vnd.oasis.opendocument.graphics");
            mimeMap.put("wax","audio/x-ms-wax");
            mimeMap.put("spc","chemical/x-galactic-spc");
            mimeMap.put("webarchive","application/x-webarchive");
            mimeMap.put("gal","chemical/x-gaussian-log");
            mimeMap.put("md","text/markdown");
            mimeMap.put("fli","video/fli");
            mimeMap.put("flac","audio/flac");
            mimeMap.put("wmv","video/x-ms-wmv");
            mimeMap.put("gsm","audio/x-gsm");
            mimeMap.put("asn","chemical/x-ncbi-asn1-spec");
            mimeMap.put("wmx","video/x-ms-wmx");
            mimeMap.put("wmlsc","application/vnd.wap.wmlscriptc");
            mimeMap.put("wml","text/vnd.wap.wml");
            mimeMap.put("crt","application/x-x509-ca-cert");
            mimeMap.put("3ga","audio/3gpp");
            mimeMap.put("7z","application/x-7z-compressed");
            mimeMap.put("igs","model/iges");
            mimeMap.put("yt","video/vnd.youtube.yt");
            mimeMap.put("rtx","text/richtext");
            mimeMap.put("msh","model/mesh");
            mimeMap.put("odc","application/vnd.oasis.opendocument.chart");
            mimeMap.put("jpg","image/jpeg");
            mimeMap.put("lrc","application/lrc");
            mimeMap.put("ttc","font/collection");
            mimeMap.put("xlsb","application/vnd.ms-excel.sheet.binary.macroenabled.12");
            mimeMap.put("shar","application/x-shar");
            mimeMap.put("csf","chemical/x-cache-csf");
            mimeMap.put("flv","video/x-flv");
            mimeMap.put("deb","application/x-debian-package");
            mimeMap.put("gz","application/gzip");
            mimeMap.put("sxi","application/vnd.sun.xml.impress");
            mimeMap.put("woff","application/font-woff");
            mimeMap.put("ods","application/vnd.oasis.opendocument.spreadsheet");
            mimeMap.put("stl","application/vnd.ms-pki.stl");
            mimeMap.put("smf","audio/sp-midi");
            mimeMap.put("xyz","chemical/x-xyz");
            mimeMap.put("lzh","application/x-lzh");
            mimeMap.put("ser","application/java-serialized-object");
            mimeMap.put("pem","application/x-pem-file");
            mimeMap.put("chrt","application/x-kchart");
            mimeMap.put("spl","application/futuresplash");
            mimeMap.put("lzx","application/x-lzx");
            mimeMap.put("ppsx","application/vnd.openxmlformats-officedocument.presentationml.slideshow");
            mimeMap.put("py","text/x-python");
            mimeMap.put("gcf","application/x-graphing-calculator");
            mimeMap.put("dcm","application/dicom");
            mimeMap.put("kwd","application/x-kword");
            mimeMap.put("xspf","application/xspf+xml");
            mimeMap.put("divx","video/divx");
            mimeMap.put("eot","application/vnd.ms-fontobject");
            
        }
        return mimeMap.get(ext);
    }
    
    public static String getExt(String mimeType){
        if(extMap==null) {
            extMap=new HashMap<>();
            extMap.put("application/x-debian-package", "deb");
            extMap.put("audio/x-sd2", "sd2");
            extMap.put("application/vnd.ms-excel", "xlt");
            extMap.put("application/x-xfig", "fig");
            extMap.put("application/x-kspread", "ksp");
            extMap.put("audio/ogg", "opus");
            extMap.put("application/x-trash", "bak");
            extMap.put("audio/midi", "xmf");
            extMap.put("application/postscript", "epsf");
            extMap.put("application/x-msdos-program", "bat");
            extMap.put("application/x-scilab", "sce");
            extMap.put("text/xml", "xml");
            extMap.put("image/x-fuji-raf", "raf");
            extMap.put("application/x-scilab", "sci");
            extMap.put("application/mxf", "mxf");
            extMap.put("text/html", "shtml");
            extMap.put("audio/csound", "sco");
            extMap.put("video/3gpp2", "3g2");
            extMap.put("audio/x-pn-realaudio", "ram");
            extMap.put("application/x-cdf", "cda");
            extMap.put("application/rar", "rar");
            extMap.put("application/x-silverlight", "scr");
            extMap.put("application/postscript", "eps3");
            extMap.put("application/x-cdf", "cdf");
            extMap.put("application/postscript", "eps2");
            extMap.put("application/x-trash", "%");
            extMap.put("image/x-cmu-raster", "ras");
            extMap.put("text/scriptlet", "sct");
            extMap.put("audio/x-dff", "dff");
            extMap.put("application/x-bcpio", "bcpio");
            extMap.put("text/x-tex", "tex");
            extMap.put("application/postscript", "ai");
            extMap.put("application/ttml+xml", "ttml");
            extMap.put("text/plain", "diff");
            extMap.put("video/vnd.mpegurl", "mxu");
            extMap.put("image/x-coreldraw", "cdr");
            extMap.put("application/vnd.stardivision.draw", "sda");
            extMap.put("application/vnd.stardivision.impress", "sdd");
            extMap.put("image/x-coreldrawtemplate", "cdt");
            extMap.put("application/vnd.stardivision.calc", "sdc");
            extMap.put("chemical/x-mdl-sdfile", "sdf");
            extMap.put("audio/basic", "au");
            extMap.put("chemical/x-cdx", "cdx");
            extMap.put("application/vnd.cinderella", "cdy");
            extMap.put("application/vnd.stardivision.impress", "sdp");
            extMap.put("application/vnd.openxmlformats-officedocument.spreadsheetml.template", "xltx");
            extMap.put("image/jp2", "jpg2");
            extMap.put("audio/aac", "aac");
            extMap.put("application/vnd.stardivision.chart", "sds");
            extMap.put("chemical/x-cxf", "cef");
            extMap.put("application/vnd.stardivision.writer", "sdw");
            extMap.put("application/x-font-pcf", "pcf.z");
            extMap.put("chemical/x-mopac-input", "mopcrt");
            extMap.put("audio/x-ms-wma", "wma");
            extMap.put("application/vnd.ms-powerpoint.presentation.macroenabled.12", "pptm");
            extMap.put("audio/3gpp", "3ga");
            extMap.put("model/x3d+binary", "x3db");
            extMap.put("application/x-ms-wmd", "wmd");
            extMap.put("audio/ac3", "ac3");
            extMap.put("application/vnd.openxmlformats-officedocument.presentationml.slideshow", "ppsx");
            extMap.put("application/pkix-cert", "cer");
            extMap.put("chemical/x-mdl-tgf", "tgf");
            extMap.put("application/vnd.ms-excel.template.macroenabled.12", "xltm");
            extMap.put("application/epub+zip", "epub");
            extMap.put("text/vnd.wap.wml", "wml");
            extMap.put("image/jpeg", "jpeg");
            extMap.put("video/3gpp", "3gp");
            extMap.put("application/vnd.openxmlformats-officedocument.wordprocessingml.template", "dotx");
            extMap.put("text/x-c++src", "cc");
            extMap.put("application/java-serialized-object", "ser");
            extMap.put("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx");
            extMap.put("video/x-ms-wmv", "wmv");
            extMap.put("chemical/x-molconn-z", "b");
            extMap.put("video/fli", "fli");
            extMap.put("text/x-csrc", "c");
            extMap.put("video/x-ms-wmx", "wmx");
            extMap.put("text/x-dsrc", "d");
            extMap.put("application/x-ms-wmz", "wmz");
            extMap.put("application/x-gtar-compressed", "tgz");
            extMap.put("text/x-chdr", "h");
            extMap.put("text/x-c++hdr", "hpp");
            extMap.put("application/vnd.ms-word.template.macroenabled.12", "dotm");
            extMap.put("application/postscript", "epsi");
            extMap.put("application/vnd.ms-powerpoint.slideshow.macroenabled.12", "ppsm");
            extMap.put("application/x-object", "o");
            extMap.put("application/vnd.font-fontforge-sfd", "sfd");
            extMap.put("application/x-xpinstall", "xpi");
            extMap.put("text/x-pascal", "p");
            extMap.put("video/x-flv", "flv");
            extMap.put("application/cu-seeme", "cu");
            extMap.put("application/x-troff", "t");
            extMap.put("image/x-xpixmap", "xpm");
            extMap.put("application/rdf+xml", "rdf");
            extMap.put("application/vnd.ms-excel.sheet.macroenabled.12", "xlsm");
            extMap.put("application/x-abiword", "abw");
            extMap.put("application/atomserv+xml", "atomsrv");
            extMap.put("application/x-kword", "kwd");
            extMap.put("application/vnd.ms-excel.sheet.binary.macroenabled.12", "xlsb");
            extMap.put("chemical/x-cactvs-binary", "ctab");
            extMap.put("application/vnd.wordperfect5.1", "wp5");
            extMap.put("application/x-trash", "~");
            extMap.put("application/x-rdp", "rdp");
            extMap.put("video/dv", "dif");
            extMap.put("text/x-sfv", "sfv");
            extMap.put("application/x-iso9660-image", "iso");
            extMap.put("application/x-internet-signup", "isp");
            extMap.put("video/dl", "dl");
            extMap.put("application/x-kword", "kwt");
            extMap.put("application/x-lyx", "lyx");
            extMap.put("chemical/x-isostar", "ist");
            extMap.put("application/vnd.ms-powerpoint.template.macroenabled.12", "potm");
            extMap.put("application/x-director", "dir");
            extMap.put("chemical/x-vmd", "vmd");
            extMap.put("application/x-latex", "latex");
            extMap.put("application/mac-binhex40", "hqx");
            extMap.put("application/octet-stream", "deploy");
            extMap.put("image/tiff", "tif");
            extMap.put("video/dv", "dv");
            extMap.put("application/x-go-sgf", "sgf");
            extMap.put("application/x-ns-proxy-autoconfig", "pac");
            extMap.put("chemical/x-jcamp-dx", "dx");
            extMap.put("application/vnd.ms-powerpoint.slide.macroenabled.12", "sldm");
            extMap.put("application/vnd.openxmlformats-officedocument.presentationml.slide", "sldx");
            extMap.put("application/vnd.stardivision.writer-global", "sgl");
            extMap.put("application/x-gnumeric", "gnumeric");
            extMap.put("application/x-lzh", "lzh");
            extMap.put("chemical/x-xtel", "xtel");
            extMap.put("chemical/x-vamas-iso14976", "vms");
            extMap.put("application/x-info", "info");
            extMap.put("audio/qcelp", "qcp");
            extMap.put("image/x-coreldrawpattern", "pat");
            extMap.put("text/x-pascal", "pas");
            extMap.put("chemical/x-chemdraw", "chm");
            extMap.put("application/vnd.wordperfect", "wpd");
            extMap.put("chemical/x-mopac-graph", "gpt");
            extMap.put("application/x-lzx", "lzx");
            extMap.put("application/ecmascript", "es");
            extMap.put("application/vnd.openxmlformats-officedocument.presentationml.presentation", "pptx");
            extMap.put("audio/aac", "adt");
            extMap.put("image/vnd.djvu", "djv");
            extMap.put("application/vnd.ms-wpl", "wpl");
            extMap.put("application/andrew-inset", "ez");
            extMap.put("audio/mobile-xmf", "mxmf");
            extMap.put("application/x-qgis", "shp");
            extMap.put("image/x-portable-bitmap", "pbm");
            extMap.put("model/x3d+vrml", "x3dv");
            extMap.put("chemical/x-embl-dl-nucleotide", "emb");
            extMap.put("application/x-maker", "fb");
            extMap.put("text/iuls", "uls");
            extMap.put("application/x-maker", "frame");
            extMap.put("chemical/x-cif", "cif");
            extMap.put("application/x-qgis", "shx");
            extMap.put("message/rfc822", "eml");
            extMap.put("application/x-android-drm-fl", "fl");
            extMap.put("application/x-maker", "fm");
            extMap.put("application/smil+xml", "smil");
            extMap.put("application/xml", "xsd");
            extMap.put("image/x-rgb", "rgb");
            extMap.put("audio/prs.sid", "sid");
            extMap.put("application/pgp-signature", "sig");
            extMap.put("application/xslt+xml", "xsl");
            extMap.put("application/x-font", "pcf");
            extMap.put("application/hta", "hta");
            extMap.put("application/x-trash", "sik");
            extMap.put("application/x-sv4crc", "sv4crc");
            extMap.put("text/x-component", "htc");
            extMap.put("application/vnd.stardivision.writer", "vor");
            extMap.put("application/json", "json");
            extMap.put("application/vnd.symbian.install", "sis");
            extMap.put("application/java-vm", "class");
            extMap.put("application/x-stuffit", "sit");
            extMap.put("application/x-tex-gf", "gf");
            extMap.put("text/html", "htm");
            extMap.put("image/pcx", "pcx");
            extMap.put("application/x-msdos-program", "dll");
            extMap.put("video/gl", "gl");
            extMap.put("chemical/x-pdb", "ent");
            extMap.put("video/x-webex", "wrf");
            extMap.put("chemical/x-pdb", "pdb");
            extMap.put("x-world/x-vrml", "wrl");
            extMap.put("application/gzip", "gz");
            extMap.put("application/pdf", "pdf");
            extMap.put("application/vnd.openxmlformats-officedocument.presentationml.template", "potx");
            extMap.put("text/x-bibtex", "bib");
            extMap.put("application/x-font", "gsf");
            extMap.put("application/x-apple-diskimage", "dmg");
            extMap.put("audio/x-gsm", "gsm");
            extMap.put("chemical/x-mmcif", "mcif");
            extMap.put("text/x-c++hdr", "hh");
            extMap.put("text/x-c++src", "c++");
            extMap.put("video/x-sgi-movie", "movie");
            extMap.put("application/octet-stream", "bin");
            extMap.put("text/scriptlet", "wsc");
            extMap.put("model/x3d+xml", "x3d");
            extMap.put("application/vnd.ms-fontobject", "eot");
            extMap.put("application/x-dms", "dms");
            extMap.put("text/x-haskell", "hs");
            extMap.put("application/x-koan", "skd");
            extMap.put("application/vnd.mozilla.xul+xml", "xul");
            extMap.put("image/x-pentax-pef", "pef");
            extMap.put("application/x-koan", "skm");
            extMap.put("application/x-texinfo", "texi");
            extMap.put("application/x-koan", "skp");
            extMap.put("chemical/x-isostar", "istr");
            extMap.put("application/x-pem-file", "pem");
            extMap.put("text/plain", "text");
            extMap.put("application/x-qgis", "qgs");
            extMap.put("image/x-adobe-dng", "dng");
            extMap.put("application/x-koan", "skt");
            extMap.put("application/x-maker", "frm");
            extMap.put("application/x-bittorrent", "torrent");
            extMap.put("application/postscript", "eps");
            extMap.put("application/x-font", "pfa");
            extMap.put("text/x-tex", "cls");
            extMap.put("application/vnd.oasis.opendocument.database", "odb");
            extMap.put("application/oda", "oda");
            extMap.put("application/x-font", "pfb");
            extMap.put("application/vnd.oasis.opendocument.chart", "odc");
            extMap.put("application/vnd.oasis.opendocument.formula", "odf");
            extMap.put("x-world/x-vrml", "vrm");
            extMap.put("image/heif-sequence", "heifs");
            extMap.put("application/vnd.debian.binary-package", "ddeb");
            extMap.put("application/vnd.oasis.opendocument.graphics", "odg");
            extMap.put("application/vnd.oasis.opendocument.image", "odi");
            extMap.put("application/msword", "doc");
            extMap.put("application/vnd.oasis.opendocument.text-master", "odm");
            extMap.put("application/vnd.oasis.opendocument.presentation", "odp");
            extMap.put("application/font-tdpfr", "pfr");
            extMap.put("application/mathematica", "nbp");
            extMap.put("application/vnd.oasis.opendocument.text", "odt");
            extMap.put("application/vnd.oasis.opendocument.spreadsheet", "ods");
            extMap.put("audio/x-aiff", "aif");
            extMap.put("application/x-hwp", "hwp");
            extMap.put("chemical/x-cml", "cml");
            extMap.put("application/x-pkcs12", "pfx");
            extMap.put("image/x-xwindowdump", "xwd");
            extMap.put("application/vnd.visio", "vsd");
            extMap.put("application/msword", "dot");
            extMap.put("audio/mpeg", "mpega");
            extMap.put("application/javascript", "js");
            extMap.put("application/x-kchart", "chrt");
            extMap.put("audio/sp-midi", "smf");
            extMap.put("application/smil+xml", "smi");
            extMap.put("application/vnd.tcpdump.pcap", "pcap");
            extMap.put("application/vnd.visio", "vst");
            extMap.put("application/x-chess-pgn", "pgn");
            extMap.put("application/vnd.visio", "vss");
            extMap.put("image/x-portable-graymap", "pgm");
            extMap.put("application/pgp-signature", "pgp");
            extMap.put("image/x-epson-erf", "erf");
            extMap.put("application/vnd.visio", "vsw");
            extMap.put("application/x-troff-man", "man");
            extMap.put("audio/basic", "snd");
            extMap.put("text/x-c++hdr", "hxx");
            extMap.put("x-world/x-vrml", "vrml");
            extMap.put("application/x-shar", "shar");
            extMap.put("video/x-ms-wvx", "wvx");
            extMap.put("video/mpeg", "mpeg1");
            extMap.put("application/vnd.rim.cod", "cod");
            extMap.put("video/mpeg", "mpeg2");
            extMap.put("video/mp4", "mpeg4");
            extMap.put("application/atom+xml", "atom");
            extMap.put("application/x-msdos-program", "com");
            extMap.put("image/x-ms-bmp", "bmp");
            extMap.put("audio/ogg", "oga");
            extMap.put("text/x-lilypond", "ly");
            extMap.put("audio/mpeg", "mpga");
            extMap.put("audio/ogg", "ogg");
            extMap.put("image/x-nikon-nef", "nef");
            extMap.put("audio/mp4", "f4a");
            extMap.put("chemical/x-compass", "cpa");
            extMap.put("audio/mp4", "f4b");
            extMap.put("image/heic-sequence", "heics");
            extMap.put("chemical/x-macmolecule", "mcm");
            extMap.put("text/markdown", "md");
            extMap.put("application/x-troff-me", "me");
            extMap.put("chemical/x-xyz", "xyz");
            extMap.put("chemical/x-alchemy", "alc");
            extMap.put("image/vnd.wap.wbmp", "wbmp");
            extMap.put("video/ogg", "ogv");
            extMap.put("application/x-freemind", "mm");
            extMap.put("application/ogg", "ogx");
            extMap.put("image/x-canon-cr2", "cr2");
            extMap.put("text/x-c++src", "cpp");
            extMap.put("audio/mp4", "f4p");
            extMap.put("image/x-corelphotopaint", "cpt");
            extMap.put("application/x-troff-ms", "ms");
            extMap.put("chemical/x-galactic-spc", "spc");
            extMap.put("text/x-setext", "etx");
            extMap.put("video/mp4", "f4v");
            extMap.put("application/msaccess", "mdb");
            extMap.put("application/x-futuresplash", "spl");
            extMap.put("font/woff", "woff");
            extMap.put("application/mathematica", "nb");
            extMap.put("text/h323", "323");
            extMap.put("audio/dsd", "dsd");
            extMap.put("application/x-netcdf", "nc");
            extMap.put("video/mpeg", "mpeg");
            extMap.put("audio/x-dsf", "dsf");
            extMap.put("audio/ogg", "spx");
            extMap.put("image/tiff", "tiff");
            extMap.put("text/x-boo", "boo");
            extMap.put("audio/amr", "amr");
            extMap.put("application/x-sql", "sql");
            extMap.put("text/text", "phps");
            extMap.put("audio/aac", "adts");
            extMap.put("application/dsptype", "tsp");
            extMap.put("text/tab-separated-values", "tsv");
            extMap.put("chemical/x-rosdal", "ros");
            extMap.put("application/x-pkcs7-crl", "crl");
            extMap.put("audio/midi", "kar");
            extMap.put("model/mesh", "mesh");
            extMap.put("video/3gpp2", "3gpp2");
            extMap.put("font/collection", "ttc");
            extMap.put("application/x-x509-ca-cert", "crt");
            extMap.put("application/x-wais-source", "src");
            extMap.put("application/x-ms-manifest", "manifest");
            extMap.put("font/ttf", "ttf");
            extMap.put("image/x-canon-crw", "crw");
            extMap.put("application/annodex", "anx");
            extMap.put("chemical/x-cactvs-binary", "cbin");
            extMap.put("image/vnd.djvu", "djvu");
            extMap.put("text/turtle", "ttl");
            extMap.put("application/x-gtar", "gtar");
            extMap.put("application/x-redhat-package-manager", "rpm");
            extMap.put("application/x-ms-application", "application");
            extMap.put("application/x-subrip", "srt");
            extMap.put("audio/csound", "csd");
            extMap.put("audio/x-scpls", "pls");
            extMap.put("chemical/x-cache-csf", "csf");
            extMap.put("text/x-csh", "csh");
            extMap.put("application/x-java-jnlp-file", "jnlp");
            extMap.put("image/x-samsung-srw", "srw");
            extMap.put("application/xslt+xml", "xslt");
            extMap.put("application/x-tex-pk", "pk");
            extMap.put("chemical/x-csml", "csm");
            extMap.put("text/x-perl", "pl");
            extMap.put("text/x-perl", "pm");
            extMap.put("text/plain", "po");
            extMap.put("application/onenote", "onepkg");
            extMap.put("text/css", "css");
            extMap.put("application/postscript", "ps");
            extMap.put("text/comma-separated-values", "csv");
            extMap.put("application/xspf+xml", "xspf");
            extMap.put("text/x-python", "py");
            extMap.put("text/vnd.sun.j2me.app-descriptor", "jad");
            extMap.put("application/mbox", "mbox");
            extMap.put("text/x-diff", "patch");
            extMap.put("application/x-msdos-program", "exe");
            extMap.put("text/x-java", "java");
            extMap.put("application/x-dvi", "dvi");
            extMap.put("audio/midi", "rtttl");
            extMap.put("application/x-jam", "jam");
            extMap.put("text/plain", "brf");
            extMap.put("audio/x-ape", "ape");
            extMap.put("application/vnd.ms-excel.addin.macroenabled.12", "xlam");
            extMap.put("application/vnd.ms-powerpoint.addin.macroenabled.12", "ppam");
            extMap.put("application/java-archive", "jar");
            extMap.put("application/vnd.ms-word.document.macroenabled.12", "docm");
            extMap.put("application/x-shockwave-flash", "swfl");
            extMap.put("application/vnd.android.package-archive", "apk");
            extMap.put("application/onenote", "onetoc2");
            extMap.put("chemical/x-csml", "csml");
            extMap.put("application/vnd.sun.xml.draw.template", "std");
            extMap.put("chemical/x-cache", "cache");
            extMap.put("application/vnd.sun.xml.calc.template", "stc");
            extMap.put("video/quicktime", "qt");
            extMap.put("application/x-trash", "old");
            extMap.put("chemical/x-ctx", "ctx");
            extMap.put("image/png", "png");
            extMap.put("video/divx", "divx");
            extMap.put("application/vnd.sun.xml.impress.template", "sti");
            extMap.put("application/vnd.ms-pki.stl", "stl");
            extMap.put("text/vcard", "vcard");
            extMap.put("application/x-texinfo", "texinfo");
            extMap.put("image/x-portable-anymap", "pnm");
            extMap.put("audio/x-pn-realaudio", "ra");
            extMap.put("application/x-ruby", "rb");
            extMap.put("chemical/x-gaussian-cube", "cub");
            extMap.put("chemical/x-crossfire", "bsd");
            extMap.put("chemical/x-mdl-rdfile", "rd");
            extMap.put("chemical/x-chem3d", "c3d");
            extMap.put("application/vnd.sun.xml.writer.template", "stw");
            extMap.put("application/x-scilab-xcos", "xcos");
            extMap.put("text/x-tex", "sty");
            extMap.put("audio/x-pn-realaudio", "rm");
            extMap.put("image/ico", "cur");
            extMap.put("chemical/x-cmdf", "cmdf");
            extMap.put("audio/midi", "mid");
            extMap.put("application/x-mif", "mif");
            extMap.put("chemical/x-mdl-sdfile", "sd");
            extMap.put("application/x-webarchive", "webarchive");
            extMap.put("application/rss+xml", "rss");
            extMap.put("application/vnd.ms-powerpoint", "pot");
            extMap.put("text/x-sh", "sh");
            extMap.put("text/markdown", "markdown");
            extMap.put("chemical/x-mol2", "mol2");
            extMap.put("application/pgp-keys", "key");
            extMap.put("application/x-director", "dxr");
            extMap.put("image/x-jg", "art");
            extMap.put("application/x-lha", "lha");
            extMap.put("chemical/x-swissprot", "sw");
            extMap.put("text/rtf", "rtf");
            extMap.put("image/svg+xml", "svg");
            extMap.put("application/onenote", "one");
            extMap.put("image/x-sony-arw", "arw");
            extMap.put("application/x-maker", "maker");
            extMap.put("image/x-portable-pixmap", "ppm");
            extMap.put("model/mesh", "silo");
            extMap.put("application/vnd.openxmlformats-officedocument.wordprocessingml.document", "docx");
            extMap.put("text/plain", "asc");
            extMap.put("text/plain", "txt");
            extMap.put("application/vnd.ms-powerpoint", "pps");
            extMap.put("application/vnd.ms-powerpoint", "ppt");
            extMap.put("video/x-ms-asf", "asf");
            extMap.put("text/x-literate-haskell", "lhs");
            extMap.put("application/javascript", "mjs");
            extMap.put("audio/midi", "rtx");
            extMap.put("text/x-tcl", "tk");
            extMap.put("text/texmacs", "tm");
            extMap.put("audio/x-mpegurl", "m3u8");
            extMap.put("chemical/x-ncbi-asn1-binary", "aso");
            extMap.put("application/x-cpio", "cpio");
            extMap.put("chemical/x-ncbi-asn1-spec", "asn");
            extMap.put("model/iges", "iges");
            extMap.put("application/x-troff", "tr");
            extMap.put("chemical/x-jcamp-dx", "jdx");
            extMap.put("video/mp2ts", "ts");
            extMap.put("audio/x-matroska", "mka");
            extMap.put("application/x-shockwave-flash", "swf");
            extMap.put("application/x-ica", "ica");
            extMap.put("video/x-ms-asf", "asx");
            extMap.put("x-conference/x-cooltalk", "ice");
            extMap.put("image/x-panasonic-rw2", "rw2");
            extMap.put("application/bbolin", "lin");
            extMap.put("chemical/x-cxf", "cxf");
            extMap.put("application/x-pkcs12", "p12");
            extMap.put("application/wasm", "wasm");
            extMap.put("image/x-icon", "ico");
            extMap.put("video/mp2t", "m2ts");
            extMap.put("text/calendar", "ics");
            extMap.put("video/x-matroska", "mkv");
            extMap.put("application/vnd.sun.xml.draw", "sxd");
            extMap.put("application/vnd.sun.xml.calc", "sxc");
            extMap.put("image/svg+xml", "svgz");
            extMap.put("text/calendar", "icz");
            extMap.put("text/x-c++src", "cxx");
            extMap.put("application/vnd.sun.xml.writer.global", "sxg");
            extMap.put("application/oebps-package+xml", "opf");
            extMap.put("application/pics-rules", "prf");
            extMap.put("application/vnd.sun.xml.impress", "sxi");
            extMap.put("application/x-quicktimeplayer", "qtl");
            extMap.put("application/vnd.sun.xml.math", "sxm");
            extMap.put("chemical/x-gaussian-checkpoint", "fchk");
            extMap.put("chemical/x-cactvs-binary", "cascii");
            extMap.put("application/vnd.sun.xml.writer", "sxw");
            extMap.put("chemical/x-ncbi-asn1-ascii", "prt");
            extMap.put("audio/ac3", "a52");
            extMap.put("image/x-photoshop", "psd");
            extMap.put("image/x-xbitmap", "xbm");
            extMap.put("audio/x-aiff", "aiff");
            extMap.put("chemical/x-macromodel-input", "mmd");
            extMap.put("application/vnd.smaf", "mmf");
            extMap.put("application/x-maker", "book");
            extMap.put("audio/x-aiff", "aifc");
            extMap.put("image/ief", "ief");
            extMap.put("text/mathml", "mml");
            extMap.put("application/x-killustrator", "kil");
            extMap.put("chemical/x-kinemage", "kin");
            extMap.put("chemical/x-gamess-input", "gam");
            extMap.put("chemical/x-gaussian-log", "gal");
            extMap.put("application/x-123", "wk");
            extMap.put("application/x-ganttproject", "gan");
            extMap.put("video/avi", "avi");
            extMap.put("application/ttml+xml", "dfxp");
            extMap.put("video/x-ms-wm", "wm");
            extMap.put("application/x-xcf", "xcf");
            extMap.put("chemical/x-gaussian-input", "gau");
            extMap.put("application/x-doom", "wad");
            extMap.put("chemical/x-embl-dl-nucleotide", "embl");
            extMap.put("application/x-ustar", "ustar");
            extMap.put("audio/csound", "orc");
            extMap.put("chemical/x-gamess-input", "gamin");
            extMap.put("application/davmount+xml", "davmount");
            extMap.put("image/x-olympus-orf", "orf");
            extMap.put("application/x-wingz", "wz");
            extMap.put("video/x-mng", "mng");
            extMap.put("image/heic", "heic");
            extMap.put("chemical/x-mdl-rxnfile", "rxn");
            extMap.put("text/vnd.wap.wmlscript", "wmls");
            extMap.put("image/heif", "heif");
            extMap.put("application/x-hdf", "hdf");
            extMap.put("audio/amr-wb", "awb");
            extMap.put("audio/x-wav", "wav");
            extMap.put("audio/mpeg", "mp2");
            extMap.put("application/xhtml+xml", "xhtml");
            extMap.put("audio/x-ms-wax", "wax");
            extMap.put("audio/mpeg", "mp1");
            extMap.put("video/mp4", "mp4");
            extMap.put("audio/mpeg", "mp3");
            extMap.put("application/vnd.wap.wmlc", "wmlc");
            extMap.put("text/x-moc", "moc");
            extMap.put("application/x-xz", "xz");
            extMap.put("text/x-pcs-gcd", "gcd");
            extMap.put("application/ld+json", "jsonld");
            extMap.put("chemical/x-gcg8-sequence", "gcg");
            extMap.put("application/x-graphing-calculator", "gcf");
            extMap.put("audio/annodex", "axa");
            extMap.put("chemical/x-mdl-molfile", "mol");
            extMap.put("chemical/x-mopac-out", "moo");
            extMap.put("x-epoc/x-sisx-app", "sisx");
            extMap.put("chemical/x-mopac-input", "mop");
            extMap.put("audio/midi", "midi");
            extMap.put("model/iges", "igs");
            extMap.put("video/quicktime", "mov");
            extMap.put("video/vnd.youtube.yt", "yt");
            extMap.put("application/vnd.android.ota", "ota");
            extMap.put("video/annodex", "axv");
            extMap.put("audio/mpeg", "mpa");
            extMap.put("font/ttf", "otf");
            extMap.put("application/zip", "zip");
            extMap.put("chemical/x-ncbi-asn1-binary", "val");
            extMap.put("chemical/x-mopac-input", "mpc");
            extMap.put("application/vnd.oasis.opendocument.text-web", "oth");
            extMap.put("application/vnd.oasis.opendocument.graphics-template", "otg");
            extMap.put("application/x-7z-compressed", "7z");
            extMap.put("video/mpeg", "mpe");
            extMap.put("application/x-comsol", "mph");
            extMap.put("video/mpeg", "mpg");
            extMap.put("application/x-webarchive-xml", "webarchivexml");
            extMap.put("application/vnd.ms-officetheme", "thmx");
            extMap.put("application/vnd.oasis.opendocument.presentation-template", "otp");
            extMap.put("application/vnd.oasis.opendocument.text-template", "ott");
            extMap.put("application/vnd.oasis.opendocument.spreadsheet-template", "ots");
            extMap.put("video/x-matroska", "mpv");
            extMap.put("image/x-nikon-nrw", "nrw");
            extMap.put("application/x-maker", "fbdoc");
            extMap.put("chemical/x-macromodel-input", "mmod");
            extMap.put("audio/flac", "flac");
            extMap.put("application/x-iphone", "iii");
            extMap.put("chemical/x-gaussian-checkpoint", "fch");
            extMap.put("application/vnd.google-earth.kml+xml", "kml");
            extMap.put("video/3gpp2", "3gp2");
            extMap.put("chemical/x-genbank", "gen");
            extMap.put("video/mpeg", "mp2v");
            extMap.put("audio/eac3", "ec3");
            extMap.put("application/onenote", "onetmp");
            extMap.put("application/x-cdlink", "vcd");
            extMap.put("text/x-vcard", "vcf");
            extMap.put("application/vnd.google-earth.kmz", "kmz");
            extMap.put("application/x-debian-package", "udeb");
            extMap.put("font/woff2", "woff2");
            extMap.put("text/x-vcalendar", "vcs");
            extMap.put("video/mpeg", "mpv2");
            extMap.put("video/mpeg", "mpv1");
            extMap.put("application/x-stuffit", "sitx");
            extMap.put("application/x-python-code", "pyc");
            extMap.put("video/mpeg", "mp1v");
            extMap.put("application/x-msi", "msi");
            extMap.put("model/mesh", "msh");
            extMap.put("image/heif", "hif");
            extMap.put("application/xhtml+xml", "xht");
            extMap.put("application/x-python-code", "pyo");
            extMap.put("application/x-troff", "roff");
            extMap.put("application/x-pkcs7-certreqresp", "p7r");
            extMap.put("application/octet-stream", "msp");
            extMap.put("chemical/x-hin", "hin");
            extMap.put("video/3gpp", "3gpp");
            extMap.put("application/octet-stream", "msu");
            extMap.put("video/mpeg", "m1v");
            extMap.put("application/x-jmol", "jmz");
            extMap.put("video/mp4", "mp4v");
            extMap.put("application/atomcat+xml", "atomcat");
            extMap.put("text/html", "html");
            extMap.put("application/lrc", "lrc");
            extMap.put("chemical/x-mopac-input", "zmt");
            extMap.put("image/x-jng", "jng");
            extMap.put("application/x-tar", "tar");
            extMap.put("image/webp", "webp");
            extMap.put("application/x-gtar-compressed", "taz");
            extMap.put("application/x-kpresenter", "kpr");
            extMap.put("image/jp2", "jp2");
            extMap.put("video/mp2t", "mts");
            extMap.put("application/x-kpresenter", "kpt");
            extMap.put("video/webm", "webm");
            extMap.put("video/mpeg", "m2t");
            extMap.put("video/mpeg", "m2v");
            extMap.put("application/x-nwc", "nwc");
            extMap.put("video/x-la-asf", "lsf");
            extMap.put("application/m3g", "m3g");
            extMap.put("chemical/x-cache", "cac");
            extMap.put("application/x-cab", "cab");
            extMap.put("image/gif", "gif");
            extMap.put("text/x-scala", "scala");
            extMap.put("text/x-c++hdr", "h++");
            extMap.put("text/cache-manifest", "appcache");
        }
        return extMap.get(mimeType);
    }
}
